modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="makeobsidiancry"
version="1.0.0"
displayName="MakeObsidianCry"
displayURL="https://github.com/HiSkyZen/MakeObsidianCry"
logoFile="pack.png"
authors="HiSkyZen"
description="Just a Simple One-Recipe Mod. Now, Make Obsidian Cry!"

[[dependencies.makeobsidiancry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
